channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==2.10.0
  - cloudpickle==3.0.0
  - dask==2024.1.0
  - importlib-metadata==7.0.1
  - jinja2==3.1.2
  - numpy==1.26.3
  - packaging==21.3
  - pandas==2.1.4
  - psutil==5.9.4
  - pyarrow==15.0.0
  - pyyaml==6.0
  - scikit-learn==1.4.0
  - scipy==1.12.0
  - sktime==0.26.0
  - xarray==2024.1.1
name: mlflow-env
